#
@base-url=http://localhost:3000

###
GET {{base-url}}

###
POST {{base-url}}

###
PUT {{base-url}}

###
DELETE {{base-url}}

###
GET {{base-url}}/static/favicon.ico HTTP/1.1

###
GET {{base-url}}/birds HTTP/1.1

###
GET {{base-url}}/birds/about HTTP/1.1

###
GET {{base-url}}/example/b

###
GET {{base-url}}/middleware
