name: 'demo-build-action'
on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: write

jobs:
  build:
    name: BUILD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Run yarn install
        uses: Borales/actions-yarn@v5.0.0
        with:
          cmd: install # 'yarn install'
      - name: Build develop bundle
        uses: Borales/actions-yarn@v5.0.0
        with:
          cmd: build # 'yarn build'
      # - name: Test the app
      #   uses: Borales/actions-yarn@v5.0.0
      #   with:
      #     cmd: test # will run `yarn test` command
