name: 'deploy-github-pages'
on:
  workflow_dispatch:
  push:
    branches: ['main']

jobs:
  deploy:
    name: DEPLOY TO GITHUB PAGES
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{runner.OS}}-build-${{hashFiles('**/yarn.lock')}}
          restore-keys: ${{runner.OS}}-build-${{runner.OS}}-
      - name: Install dependencies
        run: yarn install

      - name: Build production
        run: yarn build
        env:
          NODE_ENV: production

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
